# Generated by Django 6.0.5 on 2026-05-26 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('partially_approved', 'Partially Approved'), ('finalized', 'Finalized'), ('rejected', 'Rejected')], default='uploaded', max_length=30)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestions', to='api.client')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct Emissions'), (2, 'Scope 2 — Purchased Electricity'), (3, 'Scope 3 — Indirect Emissions')])),
                ('category', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('raw_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_co2e', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('normalized_unit', models.CharField(default='kg CO2e', max_length=50)),
                ('raw_payload', models.JSONField(default=dict)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.client')),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.dataingestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('flagged', 'Flagged'), ('unlocked', 'Unlocked'), ('batch_rejected', 'Batch Rejected'), ('exported', 'Exported')], max_length=30)),
                ('performed_by', models.CharField(max_length=150)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='api.dataingestion')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='api.emissionrecord')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('needs_review', 'Needs Review')], max_length=20)),
                ('reviewed_by', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='api.emissionrecord')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'status'], name='api_emissio_client__c589f9_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'is_suspicious'], name='api_emissio_client__eabaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['ingestion', 'status'], name='api_emissio_ingesti_4b8470_idx'),
        ),
    ]
